name: Docker Image CI

on:
  push:
    branches: [ "main" ]

  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file ./Dockerfile --tag my-image-name:$(date +%s)

      - name: Docker image push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sample-app-first-latest
          cache-from: type=registry,ref=user/sample-app-first-latest
          cache-to: type=inline
          
      
     
